name: Collect RSS Feeds

on:
  schedule:
    - cron: '0 9 * * *'  # 毎日9時に実行 (UTC時間)

jobs:
  collect_rss:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run RSS Collector
      run: python rss_collector.py

    - name: Run Tests
      run: python -m unittest test_rss_collector.py
